typedef int Data;
typedef int* ArrayPtr;
ArrayPtr initArray(int capacity);
void check(ArrayPtr ar,int num_elements,int position);
void addAfter(ArrayPtr* par, int* p_num_elements, int * pcapacity, Data data, int position);
void replaceDat(ArrayPtr ar, int num_elements, int position, Data data);
void display(ArrayPtr ar, int toDisplay);
void removeDatAfter(ArrayPtr ar, int* p_num_elements, int position);
void removeOutliers(ArrayPtr ar,int* p_num_elements,int value);
ArrayPtr smoothList(ArrayPtr ar,int* p_num_elements,int * pcapacity);
void removeDat(ArrayPtr ar, int* p_num_elements, int position);
void add(ArrayPtr* par, int* p_num_elements, int * pcapacity, Data data, int position);
